# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE.apache for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Sergio Mazzola <smazzola@iis.ee.ethz.ch>

name: lint

on: [ push, workflow_dispatch ]

jobs:

  lint-license:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check license
      uses: pulp-platform/pulp-actions/lint-license@v2.4.3
      with:
        license: |
          Copyright (\d{4}(-\d{4})?\s)?.*
          (Solderpad Hardware License, Version 0.51|Licensed under the Apache License, Version 2.0), see LICENSE.(solderpad|apache) for details.
          SPDX-License-Identifier: (SHL-0.51|Apache-2.0)
